# Generated by Django 5.1.2 on 2025-12-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('game_type', models.CharField(blank=True, max_length=32, null=True)),
                ('latest_statistic', models.CharField(blank=True, max_length=32, null=True)),
                ('rate_big', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_small', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_even', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rate_odd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pre_event_ts', models.DateTimeField(blank=True, null=True)),
                ('pre_raw', models.JSONField(blank=True, null=True)),
                ('winning_number', models.IntegerField(blank=True, null=True)),
                ('reward_numbers', models.JSONField(blank=True, null=True)),
                ('reward_type', models.CharField(blank=True, max_length=32, null=True)),
                ('winner_count', models.IntegerField(blank=True, null=True)),
                ('bet_users', models.IntegerField(blank=True, null=True)),
                ('bet_total_energy', models.BigIntegerField(blank=True, null=True)),
                ('win_total_energy', models.BigIntegerField(blank=True, null=True)),
                ('net_energy_system', models.BigIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=32, null=True)),
                ('is_reward', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('winner_event_ts', models.DateTimeField(blank=True, null=True)),
                ('winner_raw', models.JSONField(blank=True, null=True)),
                ('has_pre', models.BooleanField(default=False)),
                ('has_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
