# Generated by Django 5.2.8 on 2025-12-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameround_winner_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('STREAK', 'Streak'), ('DROUGHT', 'Drought')], max_length=20)),
                ('dimension', models.CharField(choices=[('BIG_SMALL', 'Big/Small'), ('ODD_EVEN', 'Odd/Even'), ('COLOR', 'Color')], max_length=20)),
                ('target_value', models.CharField(max_length=50)),
                ('threshold', models.IntegerField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='games.gameround')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.signalrule')),
            ],
        ),
    ]
