# Generated by Django 5.1.2 on 2025-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='prize_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='winners_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
