# Generated by Django 5.2.8 on 2025-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='winner_color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
